# Lab 12 : Neural Networks Implementation

Q. Implement the two layer network for m-samples, n-features as we discussed in class (both FP and BP) and for N layers in the hidden layer. Split the data (you can use the log. reg. data or any other one) and train your network with 80% of the data. Test your network with the test data. Report the evaluation metrics for varying number of layers in the network. Also evaluate one more activation function (ReLU/tanh) other than sigmoid function.

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
df=pd.read_csv("Logistic_regression_ls.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'Logistic_regression_ls.csv'

In [ ]:
# this data set includes 3 features 
n=int(input("Enter how many features you want to use: "))
h=int(input("Enter the number of neurons in the hidden layer"))

dat=np.array(df)
X=dat[:,:n]
y=dat[:,-1:]

print(np.shape(X))
print(np.shape(y))

(500, 3)
(500, 1)


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2,random_state=42)
r,c=np.shape(X_train)

Forward propagation:


In [ ]:
def sigmoid(x):
    z= (1/(1+np.exp(-x)))
    return z
def init_params():
    W1 = np.random.randn(h, n) * 0.01
    b1 = np.zeros((h, 1))
    W2 = np.random.randn(1, h) * 0.01
    b2 = np.zeros((1, 1))
    return W1, b1, W2, b2
def ReLU(Z):
    return np.maximum(Z, 0)

def forward_prop(W1, b1, W2, b2, X):
    Z1 = W1.dot(X.T) + b1
    A1 = sigmoid(Z1)
    Z2 = W2.dot(A1) + b2
    A2 = sigmoid(Z2)
    return Z1, A1, Z2, A2



Backward propagation

In [ ]:
def sigmoid_deriv(Z1):
   return np.multiply(sigmoid(Z1),(1-sigmoid(Z1)))
def backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y):
    m=Y.size
    dZ2 = A2 - Y.T
    dW2 = (1 / m) * dZ2.dot(A1.T)
    db2 = (1 / m) * np.sum(dZ2,axis=1,keepdims=True)
    dZ1 = np.multiply(W2.T.dot(dZ2) , (sigmoid_deriv(Z1)*Z1))
    dW1 = (1 / m) * dZ1.dot(X)
    db1 = (1 / m) * np.sum(dZ1,axis=1,keepdims=True)
    return dW1, db1, dW2, db2

def update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):
    W1 = W1 - alpha * dW1
    b1 = b1 - alpha * db1    
    W2 = W2 - alpha * dW2  
    b2 = b2 - alpha * db2    
    return W1, b1, W2, b2

def gradient_descent(X, Y, alpha, iterations):
    W1, b1, W2, b2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y)
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
        loss = -np.mean(Y * np.log(A2.T) + (1 - Y) * np.log(1 - A2.T))
    print(loss)
    return W1, b1, W2, b2

In [ ]:
W1, b1, W2, b2 = gradient_descent(X_train, y_train, 0.01, 10000)
print(W1)
print(W2)


0.21535881368789414
[[ 3.19521596e-01  3.33740420e-01  5.48638685e-01]
 [ 7.60585141e-05 -4.45032265e-04  1.54342183e-03]
 [-8.60541268e-03  5.47173718e-03  2.38272190e-02]
 [ 4.15707667e-01  4.08448642e-01  1.35327749e+00]
 [ 5.46507129e-03 -9.88388087e-03  3.15908254e-02]
 [-5.26669450e-03  5.47521832e-03 -1.15421671e-03]
 [-7.18357710e-03  2.52330903e-03  3.49767417e-02]
 [-7.29428121e-04 -5.94505403e-04  8.44100097e-03]
 [ 3.90126503e-01  3.87237556e-01  1.07131324e+00]
 [ 3.04875881e-01  3.17924069e-01  4.14035805e-01]]
[[ 1.10602674 -1.15229068 -1.08829724  3.04498666 -1.07045058 -1.12080609
  -1.1197729  -1.15524363  2.32860155  0.82798453]]


Testing the neural network on the test data

In [ ]:
Z1, A1, Z2, A2= forward_prop(W1,b1,W2,b2,X_test)
A2=np.round(A2,0)

Evaluation metrics

In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
print("Accuracy scoere= ",accuracy_score(y_test, A2.T))
print("Precision score= ",precision_score(y_test, A2.T))
print("Recall score= ",recall_score(y_test, A2.T))
print("f1 score= ",f1_score(y_test, A2.T))

Accuracy scoere=  0.98
Precision score=  0.9583333333333334
Recall score=  1.0
f1 score=  0.9787234042553191
